[012] 공공 API 조회를 위한 Network 작업
f-lab-edu/PillsUp pull request #17
Opened 2024-09-14 15:30 UTC by junlight94

🔗 작업 이슈 링크 🔗
===
[이슈 링크](https://github.com/orgs/f-lab-edu/projects/253/views/2?pane=issue&itemId=79121940)

<br>

🛠️ 작업 내역 🛠️
===
> 작업한 기능
- 공공 API 조회를 위한 Network 작업
- 조회 및 테스트를 위한 Repo, UseCase 작성

<br>

⚠️ PR 특이 사항 ⚠️
===
- 서비스키 인코딩 문제
`GdV6w9ttF1gQeOqShASaVgndIY4%2Fv1vT4QCAe0L1VHj7MjBwOv2I9TKmjZ56eh5keGMEHjEOGpFt5iasmTrkjQ%3D%3D `
서비스키를 퀴리 파라미터로 보내는 과정에서 특수문자가 인코딩되어서 일단을 baseUrl에서 pull path를 생성했습니다.

2024-09-14 15:33 UTC, junlight94 commented on PillsUp/Data/Sources/DataSource/Remote/PharmacyDataSource.swift
> +        }
이 부분을 baseURL, path, task를 나누어서 사용하고 싶었습니다.

근데 serviceKey에 있는 문자를 task에 넣으면 특수문자가 인코딩이 되어버려서 서비스키 인증이 되지 않습니다

방법을 조금 더 찾아봐야될 것 같습니다

2024-09-14 15:33 UTC, junlight94 commented on PillsUp/NetworkKit/Sources/NetworkKit/Provider.swift
> +}
Moya 프로바이더 작업입니다

2024-09-14 15:36 UTC, junlight94 reviewed
PR에 대한 코멘트입니다

2024-09-14 15:36 UTC, junlight94 commented on PillsUp/Shared/Sources/Shared/Encodable+Extension.swift
> +}
쿼리파라미터를 사용하기 위해서 Encodable을 딕셔너리로 바꾸는 extension을 추가했습니다

2024-09-14 15:36 UTC, junlight94 commented on PillsUp/NetworkKit/Sources/NetworkKit/XmlParser.swift
공공 API에서 XML형식의 데이터를 내려주어서 JSON으로 파싱하는 클래스를 따로 만들었습니다

2024-09-15 12:04 UTC, abdul0986 commented on PillsUp/Data/Sources/DataMapping/Request/PharmacyRequestDTO.swift
> +    let longitude: Double
`latitude` -> `lat`
`longitude` -> `lng`

2024-09-15 12:12 UTC, abdul0986 commented on PillsUp/Data/Sources/DataSource/Remote/PharmacyDataSource.swift
> +    }
```suggestion
    var headers: [String: String]? {
        return nil
    }
```

2024-09-15 12:18 UTC, abdul0986 commented on PillsUp/NetworkKit/Sources/NetworkKit/Configuration.swift
> +}
주요 키 값은 plist로 뺄 것 권장드립니다.

2024-09-15 12:19 UTC, abdul0986 commented on PillsUp/NetworkKit/Sources/NetworkKit/Provider.swift
> +        configuration.timeoutIntervalForRequest = 10
같은 코드가 중복 사용되었네요

2024-09-15 12:20 UTC, abdul0986 commented on PillsUp/NetworkKit/Sources/NetworkKit/XmlParser.swift
> +    private var items = [[String: Any]]()
```suggestion
    alias ItemTypes = [String: Any] 
    private var items = [ItemTypes]()
```

2024-09-15 12:21 UTC, abdul0986 commented on PillsUp/NetworkKit/Sources/NetworkKit/XmlParser.swift
> +        attributes attributeDict: [String : String] = [:]
```suggestion
        attributes attributeDict: [String: String] = [:]
```

2024-09-15 12:24 UTC, abdul0986 requested changes
피드백 반영 수정 요청드립니다.

2024-09-15 14:45 UTC, merged