[018] GitHub Action (CodeCoverage, SwiftLint)
f-lab-edu/PillsUp pull request #22
Opened 2024-09-19 14:01 UTC by junlight94

🔗 작업 이슈 링크 🔗
===
[이슈 링크](https://github.com/f-lab-edu/PillsUp/issues/18)

<br>

🛠️ 작업 내역 🛠️
===
> 작업한 기능
- github action workflow 작업
- codecoverage 적용
- swiftlint 적용

<br>

⚠️ PR 특이 사항 ⚠️
===
- 특이 사항은 없습니다!

2024-09-22 11:23 UTC, abdul0986 requested changes
코드를 푸시할 때마다 SwiftLint가 돌 수 있도록 분리 부탁드립니다.

2024-09-23 10:53 UTC, junlight94 reviewed
testCoverage CI와 Lint검사 CI 분리했습니다

2024-09-23 10:53 UTC, junlight94 commented on .github/workflows/swiftlint.yml
> +        curl -X POST --data-urlencode "payload={\"channel\": \"#lint-webhook\", \"username\": \"webhookbot\", \"text\": \"❌ SwiftLint check fail: https://github.com/${{ github.repository }}/actions/r
SwiftLint 분리했습니다
웹훅 링크는 깃헙 시크릿으로 적용하고 개인 슬랙 채널로 보고 되도록 했습니다!

![image](https://github.com/user-attachments/assets/a36fc34e-5af5-4272-80e8-e201ed91c280)

2024-09-23 10:53 UTC, junlight94 commented on PillsUp/Features/Sources/Features/Main/MainInteractor.swift
> +        try? distanceUseCase.save(distance)
swiftlint에 force try가 걸려서 수정 후 통과 확인했습니다!

2024-09-29 11:07 UTC, abdul0986 requested changes
피드백 수정 부탁드립니다~!!

2024-09-29 11:07 UTC, abdul0986 commented on .github/workflows/cicd.yml
`cicd.yaml` -> 'codecoverage.yaml`

2024-09-29 11:07 UTC, abdul0986 commented on .github/workflows/cicd.yml
> +    branches: [ "develop" ]
`develop` 브랜치가 존재하지 않습니다.

2024-09-30 15:14 UTC, merged