[015] 근처 약국 조회된 결과를 리스트로 보여줍니다.
f-lab-edu/PillsUp pull request #23
Opened 2024-09-23 15:09 UTC by junlight94

🔗 작업 이슈 링크 🔗
===
[이슈 링크](https://github.com/f-lab-edu/PillsUp/issues/15)

<br>

🛠️ 작업 내역 🛠️
===
> 작업한 기능
- 조회한 근처 약국을 리스트로 보여줍니다 (약국명, 거리)
- Pin 터치 시 Detail로 이동하기 위해서 CustomAnnotation 작업

<br>

⚠️ PR 특이 사항 ⚠️
===
- 특이 사항은 없습니다!

2024-09-23 15:09 UTC, junlight94 commented on PillsUp/Features/Sources/Features/Main/Component/PharmacyAnnotation.swift
> +    }
약국의 id로 약국 상세정보 조회가 필요해 Annotation에 id를 추가할 수 있도록 커스텀 클래스를 만들었습니다

2024-09-23 15:11 UTC, junlight94 commented on PillsUp/Features/Sources/Features/Main/MainViewController.swift
>  }
Listener 분리 피드백 적용했습니다

2024-09-29 11:23 UTC, abdul0986 requested changes
피드백 반영 부탁드립니다.

2024-09-29 11:23 UTC, abdul0986 commented on PillsUp/Features/Sources/Features/Main/Component/PharmacyTableViewCell.swift
> +        guard let distance = Double(distance) else { return "거리를 표기할 수 없습니다." }
```suggestion
        guard let distance = Double(distance) else { 
            return "거리를 표기할 수 없습니다." 
        }
```

2024-09-29 11:23 UTC, abdul0986 commented on PillsUp/Features/Sources/Features/Main/Component/PharmacyTableViewCell.swift
> +        }
```suggestion        
        if distance >= 1 {
            return "\(distance)km"
        } else {
            return "\(Int(distance * 1000))m"
        }
```

2024-09-30 15:18 UTC, merged