[003] 약국 거리 설정
f-lab-edu/PillsUp pull request #9
Opened 2024-09-06 14:44 UTC by junlight94

🔗 작업 이슈 링크 🔗
===
[이슈 링크](https://github.com/orgs/f-lab-edu/projects/253/views/2?pane=issue&itemId=76878387)

<br>

🛠️ 작업 내역 🛠️
===
> 작업한 기능
- RIB 생성 (Root, Main)
- 가까운 거리 UserDefualt에 저장 (기본 값 500)
- PickerView 사용한 가까운 거리 설정
- TestCode 작성

<br>

📈 FlowChart
===
![거리 설정 drawio](https://github.com/user-attachments/assets/46c0baa9-6bec-4387-b513-267ded7eda73)

<br>

⚠️ PR 특이 사항 ⚠️
===
- 특이 사항은 없습니다!

2024-09-06 14:50 UTC, junlight94 reviewed
PR에 대한 코멘트입니다!

2024-09-06 14:50 UTC, junlight94 commented on PillsUp/Data/Sources/DataSource/Local/AppData.swift
UserDefault를 사용해서 가까운거리를 저장하기 위해서 AppData 저장소를 만들었습니다.

2024-09-06 14:50 UTC, junlight94 commented on PillsUp/Domain/Tests/DomainTests/DistanceSettingTest.swift
테스트 코드를 작성했습니다 

작성한는 방법에 대해서 문서를 더 많이 찾아보겠습니다

2024-09-06 14:50 UTC, junlight94 commented on PillsUp/PillsUp/SceneDelegate.swift
> +        let launchRouter = RootBuilder(dependency: AppComponent()).build(navigationController)
rootBuilder에 Navigation을 직접 넘기는 방법이 조금 걸립니다.

RIBs에서 Navigation을 어떻게 사용하는지에 대해서 더 알아보겠습니다

2024-09-07 03:47 UTC, abdul0986 requested changes
피드백 반영 부탁드립니다.

2024-09-07 03:47 UTC, abdul0986 commented on PillsUp/Domain/Sources/Repository/AppDataRepository.swift
> +}
AppDataRepository와 Distance에 대한 `get`, `set`의 응집도가 약해 보입니다. Distance에 대한 처리하면 AppDataRepository보다는 좀더 Distance에 대한 처리를 담당할 수 있도록 상세화한 Repository 프로토콜을 설계하는 게 맞아 보여요

2024-09-07 03:47 UTC, abdul0986 commented on PillsUp/Domain/Sources/UseCase/DistanceSettingUseCase.swift
> +    case distanceNotMultipleOfHundred // 100단위로 끊어지지 않을 때
`distanceXXX` 프리픽스가 반복되고 있는데, 상위 enum 객체에 정의되어 있으니 아래와 같이 간소화하면 어떨까요? 

- case tooSmall 
- case tooLarge
- case notMultipleOfHundred

2024-09-07 03:47 UTC, abdul0986 commented on PillsUp/Domain/Sources/UseCase/DistanceSettingUseCase.swift
> +    case distanceNotMultipleOfHundred // 100단위로 끊어지지 않을 때
참고로 나누어 떨어지는 값은 영어식 표현으로 Round Figure라고 합니다. 이런 표현을 쓰시는 게 좀더 있어 보이긴 해요 :)

2024-09-07 13:43 UTC, junlight94 commented on PillsUp/Domain/Sources/Repository/AppDataRepository.swift
> +}
피드백 반영했습니다!
AppDataRepository -> DistanceSettingRepository 로 변경했습니다
get, set 보다는 retrieve, save 메서드로 변경했습니다

2024-09-07 13:45 UTC, junlight94 commented on PillsUp/Domain/Sources/UseCase/DistanceSettingUseCase.swift
> +    case distanceNotMultipleOfHundred // 100단위로 끊어지지 않을 때
넵!! 피드백 적용했습니다

2024-09-09 14:09 UTC, merged